--DROP TABLESPACE ts_dw_str_cls INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER sal_dw_cl CASCADE;
--
--DROP TABLESPACE ts_sal_cl INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER sal_cl CASCADE;

CREATE TABLESPACE ts_dw_str_cls
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_dw_str_cls.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER sal_dw_cl
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_str_cls;

GRANT CONNECT,RESOURCE, CREATE VIEW TO sal_dw_cl;

CREATE TABLESPACE ts_sal_cl
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sal_cl.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER sal_cl
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sal_cl;

GRANT CONNECT,RESOURCE, CREATE VIEW TO sal_cl;