--DROP TABLESPACE ts_sa_dim_client_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER dm_client CASCADE;
--
--DROP TABLESPACE ts_sa_fct_order_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER dm_order CASCADE;
--
--DROP TABLESPACE ts_sa_dim_employee_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER dm_employee CASCADE;
--
--DROP TABLESPACE ts_sa_dim_restaurant_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER dm_restaurant CASCADE;
--
--DROP TABLESPACE ts_sa_dim_dish_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER dm_dish CASCADE;
--
--DROP TABLESPACE ts_sa_dim_payment_method_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP USER dm_payment_method CASCADE;

CREATE TABLESPACE ts_sa_dim_client_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_client_01.dat'
SIZE 150M reuse
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER dm_client
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_client_01;

GRANT CONNECT,RESOURCE, CREATE VIEW TO dm_client;

CREATE TABLESPACE ts_sa_fct_order_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_fct_order_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER dm_order
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_fct_order_01;

GRANT CONNECT,RESOURCE, CREATE VIEW TO dm_order;
GRANT UNLIMITED TABLESPACE TO dm_order;

CREATE TABLESPACE ts_sa_dim_employee_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_employee_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER dm_employee
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_employee_01;

GRANT CONNECT,RESOURCE, CREATE VIEW TO dm_employee;

CREATE TABLESPACE ts_sa_dim_restaurant_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_restaurant_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER dm_restaurant
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_restaurant_01;

GRANT CONNECT,RESOURCE, CREATE VIEW TO dm_restaurant;

CREATE TABLESPACE ts_sa_dim_dish_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_dish_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER dm_dish
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_dish_01;

GRANT CONNECT,RESOURCE, CREATE VIEW TO dm_dish;
GRANT UNLIMITED TABLESPACE TO dm_dish;

CREATE TABLESPACE ts_sa_dim_payment_method_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_payment_method_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER dm_payment_method
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_dim_payment_method_01;

GRANT CONNECT,RESOURCE, CREATE VIEW TO dm_payment_method;
