/*Create a table using range partition*/
---------------------------------------------------------
DROP TABLE order_dim;

CREATE TABLE order_dim
(
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
time_id DATE,
client_id NUMBER,
CONSTRAINT ORDER_ID_PK PRIMARY KEY ( order_id ) ENABLE
)
 PARTITION BY RANGE (time_id)
 INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
 (  PARTITION order_m1_2022 VALUES LESS THAN (TO_DATE('01.04.2022','DD.MM.YYYY')),
    PARTITION order_m2_2022 VALUES LESS THAN (TO_DATE('01.05.2022','DD.MM.YYYY'))
 ) TABLESPACE lab9_01;

-- order_m2_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('23.04.2022','DD.MM.YYYY'), 1);
-- order_m1_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('24.03.2022','DD.MM.YYYY'), 1);
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('03.02.2022','DD.MM.YYYY'), 1);
--new
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('07.05.2022','DD.MM.YYYY'), 1);

SELECT * FROM order_dim PARTITION (sys_p921);
SELECT * FROM order_dim PARTITION (order_m1_2022);

SELECT partition_name, tablespace_name FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

/*Add range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

ALTER TABLE order_dim 
ADD PARTITION order_m3_2022 VALUES LESS THAN (TO_DATE('01.06.2023','DD.MM.YYYY'))
TABLESPACE lab9_02;


/*Drop range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

SELECT * FROM order_dim
ORDER BY order_id;

DELETE FROM order_dim partition (order_m1_2022);
ALTER TABLE order_dim DROP PARTITION order_m1_2022;

/*Merge range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

ALTER TABLE order_dim 
MERGE PARTITIONS order_m1_2022, order_m2_2022 INTO PARTITION order_m1_m2_2022;

/*Move range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

ALTER TABLE order_dim
MOVE PARTITION order_m1_2022 TABLESPACE lab9_02;

/*Split range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

SELECT * FROM order_dim
ORDER BY order_id;

ALTER TABLE order_dim SPLIT PARTITION 
order_m1_2022 AT (TO_DATE('01.03.2022','DD.MM.YYYY')) INTO 
( PARTITION order_m1_1_2022, PARTITION order_m1_2_2022);
      
SELECT * FROM order_dim PARTITION (order_m1_1_2022);

SELECT * FROM order_dim PARTITION (order_m1_2_2022);

/*Truncate range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

SELECT * FROM order_dim
ORDER BY order_id;

DELETE FROM order_dim PARTITION (order_m1_2022);
ALTER TABLE order_dim TRUNCATE PARTITION order_m1_2022;

