/*Create a table using hash partition*/
---------------------------------------------------------
DROP TABLE orders_by_countries;

CREATE TABLE orders_by_countries
(
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
country_name VARCHAR(10),
order_date DATE,
CONSTRAINT ORDER_ID_PK PRIMARY KEY ( order_id ) ENABLE
)
PARTITION BY HASH (country_name)
(
PARTITION Belarus,
PARTITION Russia,
PARTITION Ukraine
) TABLESPACE lab9_01;

--Belarus
INSERT INTO orders_by_countries (country_name, order_date)
VALUES ('Belarus',TO_DATE('05.12.2022','DD.MM.YYYY'));
INSERT INTO orders_by_countries (country_name, order_date)
VALUES ('Belarus',TO_DATE('25.07.2022','DD.MM.YYYY'));

--Russia
INSERT INTO orders_by_countries (country_name, order_date)
VALUES ('Russia',TO_DATE('13.03.2022','DD.MM.YYYY'));
INSERT INTO orders_by_countries (country_name, order_date)
VALUES ('Russia',TO_DATE('09.02.2022','DD.MM.YYYY'));

--Ukraine
INSERT INTO orders_by_countries (country_name, order_date)
VALUES ('Ukraine',TO_DATE('15.11.2022','DD.MM.YYYY'));

SELECT partition_name, tablespace_name FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_COUNTRIES';

/*Add hash partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_COUNTRIES';

ALTER TABLE orders_by_countries ADD PARTITION Poland TABLESPACE lab9_01;

/*Move hash partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_COUNTRIES';

ALTER TABLE orders_by_countries
MOVE PARTITION Ukraine TABLESPACE lab9_02;

/*Truncate hash partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_COUNTRIES';

DELETE FROM orders_by_countries PARTITION (Ukraine);
ALTER TABLE orders_by_countries TRUNCATE PARTITION Ukraine;

/*Coalesce hash partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_COUNTRIES';

ALTER TABLE orders_by_countries
COALESCE PARTITION;