DROP TABLE order_fact;

CREATE TABLE order_fact(
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
client_id NUMBER,
employee_id NUMBER,
restaurant_id NUMBER,
date_id DATE,
geo_id NUMBER,
total_cost DECIMAL (11,2) NOT NULL,
delivery CHAR(1) NOT NULL CHECK (delivery IN ('N','Y')),
CONSTRAINT ORDER_ID_PK PRIMARY KEY ( order_id ) ENABLE)
PARTITION BY RANGE (date_id) 
subpartition by hash(client_id) subpartitions 4
( 
PARTITION quarter_1 VALUES LESS THAN(to_date('01.04.2022','DD.MM.YYYY')) 
    ( 
    subpartition quarter_1_sub_1, 
    subpartition quarter_1_sub_2,
    subpartition quarter_1_sub_3,
    subpartition quarter_1_sub_4 
    ), 
PARTITION quarter_2 VALUES LESS THAN(to_date('01.07.2022','DD.MM.YYYY'))  
    ( 
    subpartition quarter_2_sub_1, 
    subpartition quarter_2_sub_2,
    subpartition quarter_2_sub_3,
    subpartition quarter_2_sub_4 
    ), 
PARTITION quarter_3 VALUES LESS THAN(to_date('01.10.2022','DD.MM.YYYY'))  
    ( 
    subpartition quarter_3_sub_1, 
    subpartition quarter_3_sub_2,
    subpartition quarter_3_sub_3,
    subpartition quarter_3_sub_4 
    ),
PARTITION quarter_4 VALUES LESS THAN(to_date('01.01.2023','DD.MM.YYYY'))  
    ( 
    subpartition quarter_4_sub_1, 
    subpartition quarter_4_sub_2,
    subpartition quarter_4_sub_3,
    subpartition quarter_4_sub_4 
    ) 
);