/*Create a table using range partition*/
---------------------------------------------------------
DROP TABLE order_dim;
DROP TABLE order_items;

CREATE TABLE order_dim(
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
time_id DATE,
client_id NUMBER,
CONSTRAINT ORDER_ID_PK PRIMARY KEY ( order_id ) ENABLE)
 PARTITION BY RANGE (time_id)
 (  PARTITION order_q1_2022 VALUES LESS THAN (TO_DATE('01.04.2022','DD.MM.YYYY')),
    PARTITION order_q2_2022 VALUES LESS THAN (TO_DATE('01.07.2022','DD.MM.YYYY')),
    PARTITION order_q3_2022 VALUES LESS THAN (TO_DATE('01.10.2022','DD.MM.YYYY'))
    TABLESPACE lab9_01,
    PARTITION order_q4_2022 VALUES LESS THAN (TO_DATE('01.01.2023','DD.MM.YYYY'))
    TABLESPACE lab9_01
 );
CREATE TABLE order_items
    ( order_id           NUMBER(12) NOT NULL,
      line_item_id       NUMBER(3)  NOT NULL,
      quantity           NUMBER(8),
      CONSTRAINT order_items_fk
      FOREIGN KEY(order_id) REFERENCES order_dim(order_id))
    PARTITION BY REFERENCE(order_items_fk);

-- order_q2_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('03.05.2022','DD.MM.YYYY'), 1);
-- order_q1_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('24.02.2022','DD.MM.YYYY'), 1);
--order_q3_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('03.08.2022','DD.MM.YYYY'), 1);
--order_q4_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('07.11.2022','DD.MM.YYYY'), 1);
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('15.11.2022','DD.MM.YYYY'), 1);


INSERT INTO order_items (order_id, line_item_id, quantity)
VALUES (1, 12, 10);
INSERT INTO order_items (order_id, line_item_id, quantity)
VALUES (2, 3, 10);
INSERT INTO order_items (order_id, line_item_id, quantity)
VALUES (3, 20, 10);
INSERT INTO order_items (order_id, line_item_id, quantity)
VALUES (4, 9, 10);
INSERT INTO order_items (order_id, line_item_id, quantity)
VALUES (5, 13, 10);

SELECT partition_name, tablespace_name FROM user_tab_partitions t WHERE t.table_name='ORDER_ITEMS';

SELECT * FROM order_items PARTITION (order_q2_2022);

/*Move range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_ITEMS';

ALTER TABLE order_items
MOVE PARTITION order_q2_2022 TABLESPACE lab9_02;

/*Truncate range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_ITEMS';

SELECT * FROM order_items
ORDER BY order_id;

DELETE FROM order_items PARTITION (order_q4_2022);
ALTER TABLE order_items TRUNCATE PARTITION order_q4_2022;
