DROP TABLESPACE lab9_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE lab9_02 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE lab9_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_lab9_01_data_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE lab9_02
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_lab9_02_data_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

/*Create a table using range partition*/
---------------------------------------------------------

DROP TABLE order_dim;

CREATE TABLE order_dim
(
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
time_id DATE,
client_id NUMBER,
CONSTRAINT ORDER_ID_PK PRIMARY KEY ( order_id ) ENABLE
)
 PARTITION BY RANGE (time_id)
 (  PARTITION order_q1_2022 VALUES LESS THAN (TO_DATE('01.04.2022','DD.MM.YYYY')),
    PARTITION order_q2_2022 VALUES LESS THAN (TO_DATE('01.07.2022','DD.MM.YYYY')),
    PARTITION order_q3_2022 VALUES LESS THAN (TO_DATE('01.10.2022','DD.MM.YYYY'))
    TABLESPACE lab9_01,
    PARTITION order_q4_2022 VALUES LESS THAN (TO_DATE('01.01.2023','DD.MM.YYYY'))
    TABLESPACE lab9_01
 );

-- order_q2_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('03.05.2022','DD.MM.YYYY'), 1);
-- order_q1_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('24.02.2022','DD.MM.YYYY'), 1);
--order_q3_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('03.08.2022','DD.MM.YYYY'), 1);
--order_q4_2022
INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('07.11.2022','DD.MM.YYYY'), 1);

INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('15.11.2022','DD.MM.YYYY'), 1);

SELECT * FROM order_dim
ORDER BY order_id;

SELECT * FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

SELECT * FROM order_dim PARTITION (order_q4_2022);

/*Add range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

ALTER TABLE order_dim 
ADD PARTITION order_q1_2023 VALUES LESS THAN (TO_DATE('01.04.2023','DD.MM.YYYY'))
TABLESPACE lab9_02;

/*Drop range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

SELECT * FROM order_dim
ORDER BY order_id;

DELETE FROM order_dim partition (order_q4_2022);
ALTER TABLE order_dim DROP PARTITION order_q4_2022;

/*Merge range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

ALTER TABLE order_dim 
MERGE PARTITIONS order_q3_2022, order_q4_2022 
INTO PARTITION order_q3_q4_2022;

/*Move range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

ALTER TABLE order_dim
MOVE PARTITION order_q4_2022 TABLESPACE lab9_02;

/*Split range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

SELECT * FROM order_dim
ORDER BY order_id;

SELECT * FROM order_dim PARTITION (order_q4_2022);

INSERT INTO order_dim (time_id, client_id)
VALUES (TO_DATE('25.11.2022','DD.MM.YYYY'), 1);

ALTER TABLE order_dim SPLIT PARTITION 
order_q4_2022 AT (TO_DATE('15.11.2022','DD.MM.YYYY')) INTO 
( PARTITION order_q4_1_2022, PARTITION order_q4_2_2022);
      
SELECT * FROM order_dim PARTITION (order_q4_1_2022);

SELECT * FROM order_dim PARTITION (order_q4_2_2022);

/*Truncate range partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDER_DIM';

SELECT * FROM order_dim
ORDER BY order_id;

DELETE FROM order_dim PARTITION (order_q4_2022);
ALTER TABLE order_dim TRUNCATE PARTITION order_q4_2022;