/*Create a table using list partition*/
---------------------------------------------------------
DROP TABLE orders_by_region;

CREATE TABLE orders_by_region (
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
state_code VARCHAR(2),
order_date DATE,
CONSTRAINT ORDER_ID_PK PRIMARY KEY ( order_id ) ENABLE
)
STORAGE(INITIAL 10K NEXT 20K) TABLESPACE lab9_01 
     PARTITION BY LIST (state_code) (
     PARTITION region_east
        VALUES ('MA','NY','CT','NH','ME','MD','VA','PA','NJ')
        STORAGE (INITIAL 8M) 
        TABLESPACE lab9_02,
     PARTITION region_west
        VALUES ('CA','AZ','NM','OR','WA','UT','NV','CO')
        NOLOGGING,
     PARTITION region_south
        VALUES ('TX','KY','TN','LA','MS','AR','AL','GA'),
     PARTITION region_central 
        VALUES ('OH','ND','SD','MO','IL','MI','IA'),
     PARTITION region_null
        VALUES (NULL)
);

SELECT partition_name, tablespace_name FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_REGION';

SELECT * FROM orders_by_region PARTITION (region_east);

--region_east
INSERT INTO orders_by_region (state_code, order_date)
VALUES ('MA',TO_DATE('05.12.2022','DD.MM.YYYY'));
INSERT INTO orders_by_region (state_code, order_date)
VALUES ('NY',TO_DATE('25.07.2022','DD.MM.YYYY'));

--region_west
INSERT INTO orders_by_region (state_code, order_date)
VALUES ('WA',TO_DATE('13.03.2022','DD.MM.YYYY'));
INSERT INTO orders_by_region (state_code, order_date)
VALUES ('UT',TO_DATE('09.02.2022','DD.MM.YYYY'));

--region_null
INSERT INTO orders_by_region (state_code, order_date)
VALUES (NULL,TO_DATE('15.11.2022','DD.MM.YYYY'));

SELECT * FROM orders_by_region;

/*Add list partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_REGION';

ALTER TABLE orders_by_region 
ADD PARTITION region_central_2
VALUES ('RL', 'TG')
STORAGE (INITIAL 20K NEXT 20K) TABLESPACE lab9_02
NOLOGGING;

/*Drop list partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_REGION';

SELECT * FROM orders_by_region
ORDER BY order_id;

DELETE FROM orders_by_region partition (region_null);
ALTER TABLE orders_by_region DROP PARTITION region_null;

/*Merge list partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_REGION';

ALTER TABLE orders_by_region 
MERGE PARTITIONS region_central, region_null INTO PARTITION region_central_and_null;

SELECT * FROM orders_by_region PARTITION (region_central_and_null);

/*Move list partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_REGION';

ALTER TABLE orders_by_region
MOVE PARTITION region_central TABLESPACE lab9_02;

/*Split list partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_REGION';

SELECT * FROM orders_by_region
ORDER BY order_id;

ALTER TABLE orders_by_region 
SPLIT PARTITION region_east VALUES ('CT', 'MA', 'MD')
INTO ( PARTITION region_east_1 TABLESPACE lab9_02,
       PARTITION region_east_2
       STORAGE (NEXT 2M PCTINCREASE 25)) 
PARALLEL 5;
      
SELECT * FROM orders_by_region PARTITION (region_east_1);

SELECT * FROM orders_by_region PARTITION (region_east_2);

/*Truncate list partition*/
---------------------------------------------------------
SELECT partition_name, tablespace_name 
FROM user_tab_partitions t WHERE t.table_name='ORDERS_BY_REGION';

SELECT * FROM orders_by_region
ORDER BY order_id;

DELETE FROM orders_by_region PARTITION (region_null);
ALTER TABLE orders_by_region TRUNCATE PARTITION region_null;



