--DROP TABLE order_fact;

CREATE TABLE order_fact(
order_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
client_id NUMBER,
employee_id NUMBER,
restaurant_id NUMBER,
date_id DATE,
geo_id NUMBER,
period_id NUMBER,
total_cost DECIMAL (11,2) NOT NULL,
delivery CHAR(1) NOT NULL CHECK (delivery IN ('N','Y')),
CONSTRAINT ORDER_ID_PK PRIMARY KEY ( order_id ) ENABLE)
PARTITION BY RANGE (date_id) 
subpartition by hash(client_id) subpartitions 4
( 
PARTITION quarter_1 VALUES LESS THAN(to_date('01.04.2022','DD.MM.YYYY')) 
    ( 
    subpartition quarter_1_sub_1, 
    subpartition quarter_1_sub_2,
    subpartition quarter_1_sub_3,
    subpartition quarter_1_sub_4 
    ), 
PARTITION quarter_2 VALUES LESS THAN(to_date('01.07.2022','DD.MM.YYYY'))  
    ( 
    subpartition quarter_2_sub_1, 
    subpartition quarter_2_sub_2,
    subpartition quarter_2_sub_3,
    subpartition quarter_2_sub_4 
    ), 
PARTITION quarter_3 VALUES LESS THAN(to_date('01.10.2022','DD.MM.YYYY'))  
    ( 
    subpartition quarter_3_sub_1, 
    subpartition quarter_3_sub_2,
    subpartition quarter_3_sub_3,
    subpartition quarter_3_sub_4 
    ),
PARTITION quarter_4 VALUES LESS THAN(to_date('01.01.2023','DD.MM.YYYY'))  
    ( 
    subpartition quarter_4_sub_1, 
    subpartition quarter_4_sub_2,
    subpartition quarter_4_sub_3,
    subpartition quarter_4_sub_4 
    ) 
);

ALTER TABLE order_fact
ADD CONSTRAINT client_fk
    FOREIGN KEY (client_id)
    REFERENCES dish_dimension(dish_id);

ALTER TABLE order_fact
ADD CONSTRAINT employee_fk
    FOREIGN KEY (employee_id)
    REFERENCES employee_dimension(employee_id); 
    
ALTER TABLE order_fact
ADD CONSTRAINT restaurant_fk
    FOREIGN KEY (restaurant_id)
    REFERENCES restaurant_dimension(restaurant_id); 
    
ALTER TABLE order_fact
ADD CONSTRAINT date_fk
    FOREIGN KEY (time_id)
    REFERENCES date_dimension(time_id);
    
ALTER TABLE order_fact
ADD CONSTRAINT geo_fk
    FOREIGN KEY (geo_id)
    REFERENCES DIM_geo_locations(geo_id);
    
ALTER TABLE order_fact
ADD CONSTRAINT period_fk
    FOREIGN KEY (period_id)
    REFERENCES dim_gen_period(period_id);
    

----------------------------------------------------------
--DROP TABLE dish_dimension;

CREATE TABLE dish_dimension(
dish_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
dish_name VARCHAR2(20) NOT NULL,
dish_category VARCHAR2(20) NOT NULL,
price DECIMAL (10,2) NOT NULL,
composition VARCHAR2(150) NOT NULL,
weight DECIMAL (10,2) NOT NULL,
status CHAR(1) NOT NULL CHECK (status IN ('N','Y')),
CONSTRAINT DISH_ID_PK PRIMARY KEY ( dish_id ) ENABLE);

----------------------------------------------------------
--DROP TABLE order_dish_id;

CREATE TABLE order_dish_id(
dish_amount INT NOT NULL,
order_id NUMBER,
dish_id NUMBER);

ALTER TABLE order_dish_id
ADD CONSTRAINT order_fk
    FOREIGN KEY (order_id)
    REFERENCES order_fact(order_id);
    
ALTER TABLE order_dish_id
ADD CONSTRAINT dish_fk
    FOREIGN KEY (dish_id)
    REFERENCES dish_dimension(dish_id);

----------------------------------------------------------
--DROP TABLE client_dimension;

CREATE TABLE client_dimension(
client_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
first_name VARCHAR2(20) NOT NULL,
last_name VARCHAR2(20) NOT NULL,
phone VARCHAR2(20) NOT NULL,
email VARCHAR2(40) NOT NULL,
address VARCHAR2(40),
country VARCHAR2(20) NOT NULL,
city VARCHAR2(20) NOT NULL,
status CHAR(1) NOT NULL CHECK (status IN ('N','Y')),
CONSTRAINT CLIENT_UNIQUE UNIQUE (phone, email),
CONSTRAINT CLIENT_ID_PK PRIMARY KEY ( client_id ) ENABLE);


----------------------------------------------------------
--DROP TABLE restaurant_dimension;

CREATE TABLE restaurant_dimension(
restaurant_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
phone VARCHAR2(20) NOT NULL,
email VARCHAR2(40) NOT NULL,
address VARCHAR2(40) NOT NULL,
country VARCHAR2(20) NOT NULL,
city VARCHAR2(20) NOT NULL,
duilding INT,
apartment INT,
status CHAR(1) NOT NULL CHECK (status IN ('N','Y')),
CONSTRAINT RESTAURANT_UNIQUE UNIQUE (phone, email),
CONSTRAINT RESTAURANT_ID_PK PRIMARY KEY ( restaurant_id ) ENABLE);

----------------------------------------------------------
--DROP TABLE employee_dimension;

CREATE TABLE employee_dimension(
employee_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
first_name VARCHAR2(20) NOT NULL,
last_name VARCHAR2(20) NOT NULL,
phone VARCHAR2(20) NOT NULL,
email VARCHAR2(40) NOT NULL,
department VARCHAR2(20) NOT NULL,
job_title VARCHAR2(20) NOT NULL,
restaurant_id NUMBER NOT NULL,
address VARCHAR2(40) NOT NULL,
country VARCHAR2(20) NOT NULL,
city VARCHAR2(20) NOT NULL,
duilding INT,
apartment INT,
status CHAR(1) NOT NULL CHECK (status IN ('N','Y')),
CONSTRAINT EMPLOYEE_UNIQUE UNIQUE (phone, email),
CONSTRAINT EMPLOYEE_ID_PK PRIMARY KEY ( employee_id ) ENABLE);

----------------------------------------------------------
--DROP TABLE payment_method_dimension;

CREATE TABLE payment_method_dimension(
payment_method_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
payment_method_name VARCHAR2(20),
status CHAR(1) NOT NULL CHECK (status IN ('N','Y')),
CONSTRAINT PAYMENT_METHOD_UNIQUE UNIQUE (payment_method_name),
CONSTRAINT PAYMENT_METHOD_ID_PK PRIMARY KEY ( payment_method_id ) ENABLE);

----------------------------------------------------------
--DROP TABLE gen_period_dimension;

CREATE TABLE dim_gen_period (
    period_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    valid_from     DATE NOT NULL,
    valid_to       DATE NOT NULL,
    promotion_name  VARCHAR2(100) NOT NULL,
    promotion_percent DECIMAL (5,2) NOT NULL,
    decription    VARCHAR2(100) NOT NULL,
    CONSTRAINT GEN_PERIOD_ID_PK PRIMARY KEY ( period_id) ENABLE
);

----------------------------------------------------------
--DROP TABLE DIM_geo_locations;

CREATE TABLE DIM_geo_locations (
   Geo_id             NUMBER(10,0) NOT NULL,
   Geo_group_id       NUMBER(10) NOT NULL,
   Geo_group_desc     VARCHAR2(200) NOT NULL,
   Geo_sub_group_id   NUMBER(10) NOT NULL,
   Geo_dub_group_desc VARCHAR2(200) NOT NULL,
   Geo_system_code    NUMBER(10) NOT NULL,
   Geo_system_desc    VARCHAR2(200) NOT NULL,
   Geo_region_id      NUMBER(10) NOT NULL,
   Geo_region_desc    VARCHAR2(200) NOT NULL,
   Geo_country_code_a2 VARCHAR2(200) NOT NULL,
   Geo_country_code_a3 VARCHAR2(200) NOT NULL,
   Geo_country_id     NUMBER(10) NOT NULL,
   Geo_country_desc   VARCHAR2(200) NOT NULL,
   CONSTRAINT geo_locations_dimension_PK PRIMARY KEY (Geo_id) ENABLE);

----------------------------------------------------------
--DROP TABLE date_dimension;

CREATE TABLE date_dimension(
time_id DATE,
day_name            VARCHAR2(11) NOT NULL,
    day_of_month        VARCHAR2(2) NOT NULL,
    day_of_week         VARCHAR2(1) NOT NULL,
    day_of_quarter      VARCHAR2(3) NOT NULL,
    day_of_year         VARCHAR2(3) NOT NULL,
    week_of_month       VARCHAR2(1) NOT NULL,
    week_of_quarter     VARCHAR2(2) NOT NULL,
    week_of_year        VARCHAR2(2) NOT NULL,
    month_number         VARCHAR2(2) NOT NULL,
    month_name          VARCHAR2(9) NOT NULL,
    month_of_quarter    VARCHAR2(2) NOT NULL,
    month_of_year       VARCHAR2(2) NOT NULL,
    quarter             VARCHAR2(1) NOT NULL,
    quarter_name         VARCHAR2(9) NOT NULL,
    quarter_of_year       VARCHAR2(2) NOT NULL,
    year_number          VARCHAR2(4) NOT NULL,
CONSTRAINT DATE_ID_PK PRIMARY KEY ( time_id ) ENABLE);