--DROP TABLESPACE ts_sa_clients_data_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_orders_data_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_employees_data_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_dw_cl INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_dw_data_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_dw_str_cls INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sal_cl INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_dim_client_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_fct_order_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_dim_employee_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_dim_restaurant_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_dim_dish_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
--
--DROP TABLESPACE ts_sa_dim_payment_method_01 INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE ts_sa_clients_data_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_clients_data_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_orders_data_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_orders_data_01.dat'
SIZE 200M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_employees_data_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_employees_data_01.dat'
SIZE 100M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_dw_cl
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_dw_cl.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 100M
 SEGMENT SPACE MANAGEMENT AUTO;
 
CREATE TABLESPACE ts_dw_data_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_dw_data_01.dat'
SIZE 200M
 AUTOEXTEND ON NEXT 100M
 SEGMENT SPACE MANAGEMENT AUTO;
 
CREATE TABLESPACE ts_dw_str_cls
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_dw_str_cls.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sal_cl
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sal_cl.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_dim_client_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_client_01.dat'
SIZE 150M reuse
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_fct_order_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_fct_order_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_dim_employee_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_employee_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_dim_restaurant_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_restaurant_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_dim_dish_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_dish_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE ts_sa_dim_payment_method_01
DATAFILE '/oracle/u02/oradata/VSadovskaiadb/db_ts_sa_dim_payment_method_01.dat'
SIZE 150M
AUTOEXTEND ON NEXT 50M
SEGMENT SPACE MANAGEMENT AUTO;

